# Render Deployment Configuration
services:
  - type: web
    name: pediassist
    env: python
    buildCommand: "pip install -r requirements-render.txt"
    startCommand: "python -m pediassist.web_app"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        value: sqlite:///./data/pediassist.db
      - key: SECRET_KEY
        generateValue: true
      - key: LLM_PROVIDER
        value: ollama
      - key: MODEL
        value: llama2